name: DCO Check

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  dco:
    runs-on: ubuntu-latest

    steps:
      - name: DCO Validation
        uses: tim-actions/dco@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
